import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ModalPortal from '@/components/organisms/modal/ModalPortal'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="google-site-verification"
          content="QjGJRnt3npfa1LMRUHNJTDp2TBTA-pWN-e01BwUxCT4"
        />
      </head>
      <body className=" w-screen flex flex-col items-center  ">
        <div className=" box-borders w-full max-w-[1440px] font-pretendard">
          {children}
          <ModalPortal />
        </div>
      </body>
    </html>
  )
}
